## Análisis univariado


### Variables binarias

Se analizarán las variables `AC`, `Quemacocos`, `TURBO` y `hibrido`, mediante sus frecuencias absolutas y relativas, con el objetivo de identificar la distribución de sus categorías y posibles concentraciones en los datos.

In [14]:
variables_binarias = ["AC", "Quemacocos", "TURBO", "hibrido"]

for variable in variables_binarias:
    frecuencias = muestra_1[variable].value_counts().sort_index()

    tabla = pd.DataFrame({
        "Frecuencia absoluta": frecuencias,
        "Frecuencia relativa (%)": (frecuencias / len(muestra_1) * 100).round(2)
    })

    display(tabla)

    Frecuencia absoluta  Frecuencia relativa (%)
AC
0                  2153                    75.07
1                   715                    24.93

            Frecuencia absoluta  Frecuencia relativa (%)
Quemacocos
0                          2685                    93.62
1                           183                     6.38

       Frecuencia absoluta  Frecuencia relativa (%)
TURBO
0                     2105                     73.4
1                      763                     26.6

         Frecuencia absoluta  Frecuencia relativa (%)
hibrido
0                       2862                    99.79
1                          6                     0.21

En las cuatro variables binarias se observa una mayor frecuencia de la categoría 0. Las variables `AC` y `TURBO` presentan distribuciones relativamente similares, con aproximadamente una cuarta parte de los vehículos registrados con estas características (24.93% y 26.60%, respectivamente). En contraste, la presencia de quemacocos es menos frecuente (6.38%), mientras que únicamente seis vehículos (0.21%) están identificados como híbridos. Por tanto, `Quemacocos` e `hibrido` presentan una concentración especialmente elevada en la categoría 0.

### Variables categóricas sin valores faltantes

Se analizarán las distribuciones de las variables `Marca` y `transmision` mediante sus frecuencias absolutas y relativas. Ambas variables presentan información completa en las 2,868 observaciones de la muestra.

In [16]:
# Frecuencias absolutas y relativas de las marcas
frecuencias = muestra_1["Marca"].value_counts()

tabla_marca = pd.DataFrame({
    "Frecuencia absoluta": frecuencias,
    "Frecuencia relativa (%)": (frecuencias / len(muestra_1) * 100).round(2)
})

display(tabla_marca)

# Frecuencias absolutas y relativas de las transmisiones
frecuencias = muestra_1["transmision"].value_counts()

tabla_transmision = pd.DataFrame({
    "Frecuencia absoluta": frecuencias,
    "Frecuencia relativa (%)": (frecuencias / len(muestra_1) * 100).round(2)
})

display(tabla_transmision)

                Frecuencia absoluta  Frecuencia relativa (%)
Marca
BMW                             558                    19.46
CHEVROLET                       512                    17.85
MERCEDES BENZ                   491                    17.12
AUDI                            412                    14.37
DODGE                           257                     8.96
CHRYSLER                        168                     5.86
MINI                            146                     5.09
LROVER                           74                     2.58
PONTIAC                          51                     1.78
MASERATI                         38                     1.32
ACURA                            25                     0.87
BENTLEY                          22                     0.77
GENERAL MOTORS                   19                     0.66
ASTON MARTIN                     13                     0.45
SAAB                             13                     0.45
FAW                              12                     0.42
BAIC                             10                     0.35
HUMMER                           10                     0.35
MBENZ                             9                     0.31
TESLA MOTORS                      9                     0.31
GIANT MOTORS                      5                     0.17
GMOTORS                           4                     0.14
OLDSMOBILE                        3                     0.10
TE TESLA                          3                     0.10
MCLAREN                           3                     0.10
MAYBACH                           1                     0.03

             Frecuencia absoluta  Frecuencia relativa (%)
transmision
AUT                         2033                    70.89
STD                          738                    25.73
7G-TRONIC                     38                     1.32
4MATIC                        32                     1.12
QUATTRO                       20                     0.70
DSG                            7                     0.24

La distribución de `Marca` muestra una concentración importante en cuatro denominaciones: BMW, Chevrolet, Mercedes-Benz y Audi, que representan conjuntamente el 68.80% de los vehículos de la muestra. Las 22 categorías restantes presentan participaciones individuales inferiores al 9%.

En cuanto a `transmision`, predominan las categorías `AUT` (70.89%) y `STD` (25.73%), mientras que las demás presentan frecuencias considerablemente menores. Destaca la presencia de `4MATIC` y `QUATTRO` en 52 registros, denominaciones que corresponden a sistemas de tracción integral, lo que confirma la inconsistencia conceptual identificada previamente en el diccionario de datos.

#### Tipo

Debido a que la variable `Tipo` presenta 220 categorías distintas, se mostrarán las 15 denominaciones comerciales más frecuentes, agrupando las restantes bajo la categoría `Otros tipos`.

In [17]:
# Frecuencias de las 15 categorías más comunes de Tipo
frecuencias = muestra_1["Tipo"].value_counts()

frecuencias_tipo = pd.concat([
    frecuencias.head(15),
    pd.Series({"Otros tipos": frecuencias.iloc[15:].sum()})
])

tabla_tipo = pd.DataFrame({
    "Frecuencia absoluta": frecuencias_tipo,
    "Frecuencia relativa (%)": (frecuencias_tipo / len(muestra_1) * 100).round(2)
})

display(tabla_tipo)

             Frecuencia absoluta  Frecuencia relativa (%)
SERIE 3                      165                     5.75
A3                            99                     3.45
SERIE 1                       77                     2.68
SERIE C                       77                     2.68
CLASICO                       77                     2.68
A4                            71                     2.48
CHEVY                         63                     2.20
SERIE 5                       55                     1.92
SERIE X5                      55                     1.92
SERIE E                       53                     1.85
SUBURBAN                      52                     1.81
SERIE M                       43                     1.50
MASERATI                      38                     1.32
VOYAGER                       38                     1.32
NEON                          36                     1.26
Otros tipos                 1869                    65.17

La variable `Tipo` presenta una distribución dispersa entre sus 220 categorías. La denominación más frecuente es `SERIE 3`, con 165 observaciones (5.75%), seguida de `A3`, con 99 (3.45%). En conjunto, las 15 categorías más frecuentes representan el 34.83% de la muestra, mientras que las 205 restantes concentran el 65.17%.

Estos resultados muestran una amplia diversidad de denominaciones comerciales, sin que exista una categoría claramente predominante. Asimismo, se observan diferentes niveles de especificidad en las denominaciones, como se documentó previamente en el diccionario de datos.

### Variables categóricas con valores faltantes

Se analizarán las variables `motor` y `traccion`, considerando tanto su distribución sobre el total de observaciones como su distribución entre los registros con información disponible.

#### Motor

In [18]:
# Distribución de motor sobre toda la muestra
frecuencias = muestra_1["motor"].value_counts(dropna=False)

tabla_motor = pd.DataFrame({
    "Frecuencia absoluta": frecuencias,
    "Frecuencia relativa (%)": (frecuencias / len(muestra_1) * 100).round(2)
})

tabla_motor.index = tabla_motor.index.fillna("Sin dato")

display(tabla_motor)

# Distribución entre los registros con motor informado
frecuencias_validas = muestra_1["motor"].value_counts()

tabla_motor_validos = pd.DataFrame({
    "Frecuencia absoluta": frecuencias_validas,
    "Frecuencia relativa (%)": (
        frecuencias_validas / muestra_1["motor"].notna().sum() * 100
    ).round(2)
})

display(tabla_motor_validos)

          Frecuencia absoluta  Frecuencia relativa (%)
motor
Sin dato                 1997                    69.63
L4                        454                    15.83
V6                        181                     6.31
V8                        165                     5.75
L6                         39                     1.36
V12                        18                     0.63
V10                        14                     0.49

       Frecuencia absoluta  Frecuencia relativa (%)
motor
L4                     454                    52.12
V6                     181                    20.78
V8                     165                    18.94
L6                      39                     4.48
V12                     18                     2.07
V10                     14                     1.61

La variable `motor` presenta 1,997 valores faltantes, equivalentes al 69.63% de la muestra, por lo que únicamente se dispone de información para 871 vehículos.

Entre los registros con información disponible, predomina la configuración `L4`, con 454 observaciones (52.12%), seguida de `V6` (20.78%) y `V8` (18.94%). Las configuraciones `L6`, `V12` y `V10` presentan frecuencias considerablemente menores.

La elevada proporción de valores faltantes limita la caracterización de esta variable para el conjunto de la muestra y deberá considerarse durante el proceso de homologación.

#### Motor

In [19]:
# Distribución de tracción sobre toda la muestra
frecuencias = muestra_1["traccion"].value_counts(dropna=False)

tabla_traccion = pd.DataFrame({
    "Frecuencia absoluta": frecuencias,
    "Frecuencia relativa (%)": (frecuencias / len(muestra_1) * 100).round(2)
})

tabla_traccion.index = tabla_traccion.index.fillna("Sin dato")

display(tabla_traccion)

# Distribución entre los registros con tracción informada
frecuencias_validas = muestra_1["traccion"].value_counts()

tabla_traccion_validos = pd.DataFrame({
    "Frecuencia absoluta": frecuencias_validas,
    "Frecuencia relativa (%)": (
        frecuencias_validas / muestra_1["traccion"].notna().sum() * 100
    ).round(2)
})

display(tabla_traccion_validos)

          Frecuencia absoluta  Frecuencia relativa (%)
traccion
Sin dato                 2707                    94.39
4X2                        50                     1.74
4X4                        46                     1.60
AWD                        35                     1.22
4WD                        19                     0.66
2WD                        11                     0.38

          Frecuencia absoluta  Frecuencia relativa (%)
traccion
4X2                        50                    31.06
4X4                        46                    28.57
AWD                        35                    21.74
4WD                        19                    11.80
2WD                        11                     6.83

La variable `traccion` presenta 2,707 valores faltantes, equivalentes al 94.39% de la muestra, por lo que únicamente se dispone de información para 161 vehículos.

Entre los registros con información disponible, predominan las categorías `4X2` (31.06%), `4X4` (28.57%) y `AWD` (21.74%), mientras que `4WD` y `2WD` representan el 11.80% y 6.83%, respectivamente.

La elevada proporción de valores faltantes limita considerablemente el análisis de esta variable. Además, como se identificó en el diccionario de datos, existen denominaciones con significados equivalentes a nivel general, cuya posible homologación deberá evaluarse durante la ingeniería de datos.

### Variables cuantitativas

Se analizarán las variables `Modelo` y `cilindrada` mediante estadísticos descriptivos y distribuciones de frecuencias. El objetivo es caracterizar sus valores, identificar su tendencia central y dispersión, así como examinar posibles concentraciones en la muestra.

#### Modelo

La variable `Modelo` representa el año-modelo del vehículo y no presenta valores faltantes, por lo que se analizarán las 2,868 observaciones.

Se calcularán el mínimo, máximo, media, mediana, moda, cuartiles y desviación estándar. Adicionalmente, se obtendrán las frecuencias absolutas y relativas de cada año-modelo, con el propósito de identificar los años más frecuentes y la distribución temporal de los vehículos.

#### Modelo

In [20]:

modelo = muestra_1["Modelo"]

# Estadísticos descriptivos del año-modelo
resumen_modelo = pd.Series({
    "Mínimo": modelo.min(),
    "Q1": modelo.quantile(0.25),
    "Mediana": modelo.median(),
    "Media": round(modelo.mean(), 2),
    "Q3": modelo.quantile(0.75),
    "Máximo": modelo.max(),
    "Moda": modelo.mode().tolist(),
    "Desviación estándar": round(modelo.std(), 2)
})

display(resumen_modelo.to_frame("Valor"))

# Distribución de frecuencias por año-modelo
frecuencias = modelo.value_counts().sort_index()

tabla_modelo = pd.DataFrame({
    "Frecuencia absoluta": frecuencias,
    "Frecuencia relativa (%)": (frecuencias / len(modelo) * 100).round(2)
})

display(tabla_modelo)

                       Valor
Mínimo                  1978
Q1                    2004.0
Mediana               2010.0
Media                2008.53
Q3                    2015.0
Máximo                  2020
Moda                  [2014]
Desviación estándar     7.88

        Frecuencia absoluta  Frecuencia relativa (%)
Modelo
1978                      3                     0.10
1979                      2                     0.07
1980                      4                     0.14
1981                      4                     0.14
1982                      6                     0.21
1983                      6                     0.21
1984                      7                     0.24
1985                     12                     0.42
1986                     11                     0.38
1987                     13                     0.45
1988                      9                     0.31
1989                      7                     0.24
1990                     11                     0.38
1991                     17                     0.59
1992                     16                     0.56
1993                     20                     0.70
1994                     24                     0.84
1995                     31                     1.08
1996                     29                     1.01
1997                     28                     0.98
1998                     47                     1.64
1999                     46                     1.60
2000                     64                     2.23
2001                     66                     2.30
2002                     76                     2.65
2003                     87                     3.03
2004                     99                     3.45
2005                    108                     3.77
2006                    129                     4.50
2007                    137                     4.78
2008                    133                     4.64
2009                    136                     4.74
2010                    140                     4.88
2011                    111                     3.87
2012                    154                     5.37
2013                    152                     5.30
2014                    197                     6.87
2015                    168                     5.86
2016                    163                     5.68
2017                    140                     4.88
2018                    116                     4.04
2019                     94                     3.28
2020                     45                     1.57

La variable `Modelo` presenta valores comprendidos entre 1978 y 2020, con una media de 2008.53 y una mediana de 2010. El 50% central de las observaciones se encuentra aproximadamente entre los años-modelo 2004 y 2015, mientras que la desviación estándar es de 7.88 años.

El año-modelo más frecuente es 2014, con 197 vehículos (6.87%). La distribución muestra una mayor concentración en los años más recientes del intervalo observado, mientras que los vehículos correspondientes a las décadas de 1970, 1980 y 1990 presentan frecuencias considerablemente menores.

#### Cilindrada

In [21]:

cilindrada = muestra_1["cilindrada"]
cilindrada_validos = cilindrada.dropna()

# Estadísticos descriptivos de cilindrada
resumen_cilindrada = pd.Series({
    "Observaciones válidas": len(cilindrada_validos),
    "Valores faltantes": cilindrada.isna().sum(),
    "Mínimo": cilindrada_validos.min(),
    "Q1": cilindrada_validos.quantile(0.25),
    "Mediana": cilindrada_validos.median(),
    "Media": round(cilindrada_validos.mean(), 2),
    "Q3": cilindrada_validos.quantile(0.75),
    "Máximo": cilindrada_validos.max(),
    "Moda": cilindrada_validos.mode().tolist(),
    "Desviación estándar": round(cilindrada_validos.std(), 2)
})

display(resumen_cilindrada.to_frame("Valor"))

# Frecuencias sobre las 2,868 observaciones
frecuencias = cilindrada.value_counts(dropna=False).sort_index()

tabla_cilindrada = pd.DataFrame({
    "Frecuencia absoluta": frecuencias,
    "Frecuencia relativa (%)": (frecuencias / len(cilindrada) * 100).round(2)
})

tabla_cilindrada.index = tabla_cilindrada.index.fillna("Sin dato")
display(tabla_cilindrada)

# Frecuencias únicamente entre los registros disponibles
frecuencias_validas = cilindrada_validos.value_counts().sort_index()

tabla_cilindrada_validos = pd.DataFrame({
    "Frecuencia absoluta": frecuencias_validas,
    "Frecuencia relativa (%)": (
        frecuencias_validas / len(cilindrada_validos) * 100
    ).round(2)
})

display(tabla_cilindrada_validos)

                       Valor
Observaciones válidas   1047
Valores faltantes       1821
Mínimo                   1.0
Q1                       1.8
Mediana                  2.1
Media                    2.8
Q3                       3.6
Máximo                   6.4
Moda                   [2.0]
Desviación estándar     1.32

            Frecuencia absoluta  Frecuencia relativa (%)
cilindrada
1.0                           6                     0.21
1.1                           3                     0.10
1.2                          11                     0.38
1.3                           7                     0.24
1.4                          72                     2.51
1.5                          27                     0.94
1.6                          82                     2.86
1.8                          77                     2.68
2.0                         229                     7.98
2.1                          10                     0.35
2.2                           8                     0.28
2.4                          19                     0.66
2.5                          30                     1.05
2.7                           4                     0.14
3.0                         141                     4.92
3.2                          24                     0.84
3.3                           6                     0.21
3.5                          19                     0.66
3.6                          43                     1.50
3.7                           4                     0.14
3.8                          13                     0.45
4.0                          32                     1.12
4.2                          32                     1.12
4.4                          24                     0.84
4.6                           3                     0.10
4.7                           5                     0.17
4.8                           5                     0.17
5.0                          13                     0.45
5.2                          16                     0.56
5.3                           9                     0.31
5.5                          18                     0.63
5.7                           9                     0.31
6.0                          29                     1.01
6.2                          11                     0.38
6.3                           4                     0.14
6.4                           2                     0.07
Sin dato                   1821                    63.49

            Frecuencia absoluta  Frecuencia relativa (%)
cilindrada
1.0                           6                     0.57
1.1                           3                     0.29
1.2                          11                     1.05
1.3                           7                     0.67
1.4                          72                     6.88
1.5                          27                     2.58
1.6                          82                     7.83
1.8                          77                     7.35
2.0                         229                    21.87
2.1                          10                     0.96
2.2                           8                     0.76
2.4                          19                     1.81
2.5                          30                     2.87
2.7                           4                     0.38
3.0                         141                    13.47
3.2                          24                     2.29
3.3                           6                     0.57
3.5                          19                     1.81
3.6                          43                     4.11
3.7                           4                     0.38
3.8                          13                     1.24
4.0                          32                     3.06
4.2                          32                     3.06
4.4                          24                     2.29
4.6                           3                     0.29
4.7                           5                     0.48
4.8                           5                     0.48
5.0                          13                     1.24
5.2                          16                     1.53
5.3                           9                     0.86
5.5                          18                     1.72
5.7                           9                     0.86
6.0                          29                     2.77
6.2                          11                     1.05
6.3                           4                     0.38
6.4                           2                     0.19

La variable `cilindrada` presenta 1,821 valores faltantes (63.49%), por lo que los estadísticos descriptivos se calcularon únicamente sobre las 1,047 observaciones disponibles.

Los valores registrados se encuentran entre 1.0 y 6.4 litros, con una media de 2.8 litros y una mediana de 2.1 litros. El 50% central de las observaciones se sitúa entre 1.8 y 3.6 litros, con una desviación estándar de 1.32 litros.

La cilindrada más frecuente es 2.0 litros, presente en 229 vehículos (21.87% de los registros disponibles), seguida de 3.0 litros, con 141 vehículos (13.47%). La diferencia entre la media y la mediana sugiere una distribución con cierta asimetría hacia valores elevados.

Finalmente, la elevada proporción de valores faltantes limita la representatividad de estos resultados respecto al conjunto de la muestra y deberá considerarse durante la ingeniería de datos.

### Variable cualitativa textual

#### descripcion

La variable `descripcion` contiene información comercial y técnica de los vehículos mediante cadenas de caracteres. Presenta 1,737 valores distintos entre las 2,868 observaciones de la muestra y no contiene valores faltantes.

Debido a su elevada cardinalidad, el análisis se centrará en estudiar la diversidad y repetición de las descripciones. Para ello, se calculará la proporción de descripciones distintas respecto al total de observaciones, así como la cantidad y proporción de descripciones que aparecen una sola vez o múltiples veces.

Adicionalmente, se distinguirá entre el porcentaje de descripciones distintas que se repiten y el porcentaje de observaciones que contienen descripciones repetidas.

In [23]:


descripcion = muestra_1["descripcion"]
frecuencias = descripcion.value_counts()

total = len(descripcion)
distintas = len(frecuencias)
unicas = (frecuencias == 1).sum()
repetidas = (frecuencias > 1).sum()
observaciones_repetidas = frecuencias[frecuencias > 1].sum()

tabla_descripcion = pd.DataFrame({
    "Indicador": [
        "Descripciones distintas",
        "Descripciones que aparecen una sola vez",
        "Descripciones que aparecen más de una vez",
        "Observaciones con descripción única",
        "Observaciones con descripción repetida"
    ],
    "Frecuencia absoluta": [
        distintas, unicas, repetidas, unicas, observaciones_repetidas
    ],
    "Frecuencia relativa (%)": [
        distintas / total * 100,
        unicas / distintas * 100,
        repetidas / distintas * 100,
        unicas / total * 100,
        observaciones_repetidas / total * 100
    ],
    "Base del porcentaje": [
        "Total de observaciones",
        "Descripciones distintas",
        "Descripciones distintas",
        "Total de observaciones",
        "Total de observaciones"
    ]
})

tabla_descripcion["Frecuencia relativa (%)"] = (
    tabla_descripcion["Frecuencia relativa (%)"].round(2)
)

display(tabla_descripcion)

,Indicador,Frecuencia absoluta,Frecuencia relativa (%),Base del porcentaje
0,Descripciones distintas,1737,60.56,Total de observaciones
1,Descripciones que aparecen una sola vez,999,57.51,Descripciones distintas
2,Descripciones que aparecen más de una vez,738,42.49,Descripciones distintas
3,Observaciones con descripción única,999,34.83,Total de observaciones
4,Observaciones con descripción repetida,1869,65.17,Total de observaciones